server:
  port: 8006
#  servlet:
#    context-path: /ver1
spring:
  application:
    name: hello
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.6:8848
        register-enabled: true
        metadata:
          nacos.instanceId: ${spring.application.name}#${random.value}
      config:
        server-addr: 192.168.1.6:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.6:5432/springboot8001
    username: postgres
    password: postgres

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
      additional-paths: src/main/java #重启目录

#mybatis-plus:
#  mapper-locations: org/example/mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息

logging:
  file:
    path: log/demo-8006
    max-size: 10MB