server:
  port: 8005
spring:
  application:
    name: hello
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.81:8848
        register-enabled: true
      config:
        server-addr: 192.168.10.81:8848
